### ISSUE TITLE
Skip CI for changes in *.md files

### ISSUE THREAD

**Issue by erlend-aasland** [python/core-workflow#474]
In python/cpython#95206, which only changes a single `.md` file, the `.github/workflows/build.yml` CI is run, which is definitely not needed. I'm pretty sure this can be fixed by adding a `path:` rule to `.github/workflows/build.yml` (and probably also `.github/workflows/doc.yml`). Something like this should suffice:

```yml
on:
  pull_request:
    paths:
      - '!**/*.md'
```
